name: Python App Tests with pytest

on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout git repo
      uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install Poetry
      run: |
        curl -sSL https://install.python.poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install Dependencies
      run: |
        poetry install
    - name: Run pytest
      run: |
        cd tests
        poetry run pytest tests